{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.additionalLabels }}
  {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4}}
  {{- end }}
  name: {{ template "haproxy.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
spec:
  endpoints:
    - targetPort: {{ .Values.serviceMonitor.metricsPort }}
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.metricsPath }}
  jobLabel: {{ template "haproxy.fullname" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "haproxy.selectorLabels" . | nindent 6 }}
  {{- with .Values.serviceMonitor.targetLabels }}
  targetLabels:
  {{ toYaml . | trim | indent 4 -}}
  {{- end }}
  {{- with .Values.serviceMonitor.podTargetLabels }}
  podTargetLabels:
  {{ toYaml . | trim | indent 4 -}}
  {{- end }}
{{- end }}